config/routes.rb
CommonBacklog::Application.routes.draw do
  
  match '/programs/prioritize' => 'programs#prioritize'

  resources :plans

  resources :projects
  resources :programs do
    resources :objectives
  end

  root :to => 'programs#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :title
  
  has_one :plan
  has_many :projects, through: :plan
  has_many :objectives, order: 'position'
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def prioritize
    params[:objective_ids].each_index { |i| Objective.find(params[:objective_ids][i]).update_attribute 'position', i }
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.haml
= form_for @program do |f|
  -if @program.errors.any?
    #error_explanation
      %h2= "#{pluralize(@program.errors.count, "error")} prohibited this program from being saved:"
      %ul
        - @program.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/programs/edit.html.haml
%h1 Editing program

= render 'form'

= link_to 'Show', @program
\|
= link_to 'Back', programs_path

app/views/programs/index.html.haml
- @programs.each do |program|
  .program
    %h2.page-header
      = program.title
    .row
      .span6
        %h3
          - if program.objectives.size < 1
            = link_to "Backlog", new_program_objective_path(program)
          - else
            = link_to "Backlog", program
        .size
          - if program.objectives.size > 0
            %h6= "#{program.objectives.size} Objectives"
          - else
            %p= "The Backlog is a prioritized list of objectives."
        %br
        %h3
          = link_to "Plan", program.plan
        .size
          - if program.plan.objectives.size > 0
            %h6= "#{program.plan.objectives.size} Objectives planned"
          - else
            %p= "The Plan allows you track the progress of your objectives."
      .span6
        %h3
          Program Projects
          - program.projects.each do |project|
            %h3= link_to project.title, project

app/views/programs/new.html.haml
%h1 New program

= render 'form'

= link_to 'Back', programs_path

app/views/programs/show.html.haml
%h1.page-header
  Capture and Prioritize
.row
  .span6
    .actions
      = link_to "New Objective", new_program_objective_path(@program), class: 'btn'
    .row
      .span3
        %h6 
          Objectives
      .span1
        %h6
          Value
      .span1
        %h6
          Size
      .span1
        %h6
          Compare
    %ul.objectives.unstyled
      -@program.objectives.each do |objective|
        %li.objective{'data-objective-id' => objective.id }
          .row
            .span3
              .handle.icon-align-justify
              = truncate(objective.title, length: 32)
              = link_to edit_program_objective_path(objective.program, objective), title: objective.description, rel: 'tooltip' do
                .icon-edit
            .span1.value{title: '', rel: 'tooltip'}
              .fill
            .span1.cost{title: '', rel: 'tooltip'}
              .fill
            .span1.compare_column
              = check_box "compare", objective.id, :class => 'compare_checkbox pull-right', 'data-title' => objective.title, 'data-value' => objective.value, 'data-cost' => objective.cost, 'data-ratio' => objective.ratio, 'data-id' => objective.id
  .span6
    = link_to "Start Planning", @program.plan, class: 'btn pull-right btn-primary'
    %ul#charts.nav.nav-tabs
      %li.active
        %a{href: '#first_chart', 'data-toggle' => 'tab'}
          Chart
      %li
        %a{href: '#second_chart', 'data-toggle' => 'tab'}
          Ratios
      %li
        %a{href: '#third_chart', 'data-toggle' => 'tab'}
          Graph
    .tab-content
      .tab-pane#first_chart.active
        #chart
      .tab-pane#second_chart
        #ratio_chart
      .tab-pane#third_chart
        #graph_chart