config/routes.rb
CommonBacklog::Application.routes.draw do
  
  match '/programs/prioritize' => 'programs#prioritize'

  resources :plans

  resources :projects
  resources :programs do
    resources :objectives
  end

  root :to => 'programs#index'

end

app/models/objective.rb
class Objective < ActiveRecord::Base
  belongs_to :plan
  belongs_to :program
  attr_accessible :title, :cost, :value, :program_id, :plan_id, :position, :description
  validates :title, presence: :true
  validates :description, presence: :true
  validates :cost, presence: :true
  validates :value, presence: :true
  validates_numericality_of :cost, :only_integer => true, :message => "Can only be whole number."
  validates_numericality_of :value, :only_integer => true, :message => "Can only be whole number."
  acts_as_list scope: :program
  def ratio
    (value * 100 / cost)
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @objectives }
    end
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
    @objective = Objective.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @objective }
    end
  end

  # GET /objectives/new
  # GET /objectives/new.json
  def new
    @objective = Objective.new
    @objective.program = Program.find params[:program_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @objective }
    end
  end

  # GET /objectives/1/edit
  def edit
    @objective = Objective.find(params[:id])
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(params[:objective])
    @objective.program = Program.find params[:program_id] 

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective.program, notice: 'Objective was successfully created.' }
        format.json { render json: @objective, status: :created, location: @objective }
      else
        format.html { render action: "new" }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /objectives/1
  # PUT /objectives/1.json
  def update
    @objective = Objective.find(params[:id])

    respond_to do |format|
      if @objective.update_attributes(params[:objective])
        format.html { redirect_to @objective.program, notice: 'Objective was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective = Objective.find(params[:id])
    @objective.destroy

    respond_to do |format|
      format.html { redirect_to @objective.program, notice: 'Objective was successfully deleted.'  }
      format.json { head :no_content }
    end
  end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.haml
= form_for  [@objective.program, @objective] do |f|
  -if @objective.errors.any?
    #error_explanation
      %h2= "#{pluralize(@objective.errors.count, "error")} prohibited this objective from being saved:"
      %ul
        - @objective.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label "Purpose"
    = f.text_area :description, :rows => 3, :cols => 40, :placeholder => "Describe the purpose of this objective"
  .field
    = f.label :value
    = f.number_field :value
  .field
    = f.label "Size"
    = f.number_field :cost
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/objectives/edit.html.haml
%h1 Editing objective

= render 'form'

= link_to 'Back', @objective.program

app/views/objectives/index.html.haml
%h1 Listing objectives

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @objectives.each do |objective|
    %tr
      %td= objective.title
      %td= link_to 'Show', objective
      %td= link_to 'Edit', edit_objective_path(objective)
      %td= link_to 'Destroy', objective, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Objective', new_objective_path

app/views/objectives/new.html.haml
%h1 New objective

= render 'form'

app/views/objectives/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @objective.title

= link_to 'Edit', edit_objective_path(@objective)
\|
= link_to 'Back', objectives_path