config/routes.rb
CommonBacklog::Application.routes.draw do
  
  match '/programs/prioritize' => 'programs#prioritize'

  resources :plans

  resources :projects
  resources :programs do
    resources :objectives
  end

  root :to => 'programs#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :title, :program_id
  
  belongs_to :program
  has_many :objectives
  has_many :projects
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_backlog_list.html.haml
%ul.objectives.unstyled
  - @plan.program.objectives.each do |objective|
    %li.objective
      .objective_container
        %span.left_handle
        .title
          = truncate(objective.title)
        %span.right_handle
.actions
  = link_to "Re-Prioritize", @plan.program
  = link_to "New Objective", new_program_objective_path(@plan.program), class: 'pull-right'

app/views/plans/_form.html.haml
= form_for @plan do |f|
  -if @plan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@plan.errors.count, "error")} prohibited this plan from being saved:"
      %ul
        - @plan.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/plans/edit.html.haml
%h1 Editing plan

= render 'form'

= link_to 'Show', @plan
\|
= link_to 'Back', plans_path

app/views/plans/index.html.haml
%h1 Listing plans

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @plans.each do |plan|
    %tr
      %td= plan.title
      %td= link_to 'Show', plan
      %td= link_to 'Edit', edit_plan_path(plan)
      %td= link_to 'Destroy', plan, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Plan', new_plan_path

app/views/plans/new.html.haml
%h1 New plan

= render 'form'

= link_to 'Back', plans_path

app/views/plans/show.html.haml
#backlog_popover{rel: 'popover', title: 'Prioritized Backlog', content: "" }

#droppable
  = image_tag('online_retail_timeline_1.png')

#backlog-list{'style' => 'display: none;'}
  = render partial: 'backlog_list'